# -- Global values shared across all subcharts.
global:
  image:
    registry: ""
    tag: "latest"
    pullPolicy: IfNotPresent
  aws:
    region: eu-west-2
    account: ""
  gateway:
    name: "" # defaults to <release>-meteo

# -- Producer subchart overrides.
producer:
  enabled: false

# -- Consumer subchart overrides.
consumer:
  enabled: false

# -- API subchart overrides.
api:
  enabled: false

envoy:
  enabled: true

cert-manager:
  enabled: true
dev:
  enabled: true
