name: Main Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  producer:
    name: Producer
    uses: ./.github/workflows/reusable-svc-build-test.yml
    with:
      service: producer
      upload-coverage: true
      push-image: true
      image-tag: ${{ github.sha }}

  consumer:
    name: Consumer
    uses: ./.github/workflows/reusable-svc-build-test.yml
    with:
      service: consumer
      upload-coverage: true
      push-image: true
      image-tag: ${{ github.sha }}

  api:
    name: API
    uses: ./.github/workflows/reusable-svc-build-test.yml
    with:
      service: api
      upload-coverage: true
      push-image: true
      image-tag: ${{ github.sha }}
